project:
  type: website
website:
  title: "Jesus LM"
  page-navigation: true
  page-footer:
    background: "#f8f8f8"
    center:
      - text: Tableau
        href: https://tinyurl.com/jesus-tableau
      - text: "&emsp; &copy; 2025 &emsp;"
      - icon: medium
        href: https://medium.com/@jesuslm
      - icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lm
      - icon: twitter
        href: https://x.com/j3suslm
  
  navbar:
    right:
      #- about.qmd
      - icon: medium
        href: https://medium.com/@jesuslm
      - icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lm
      - icon: twitter
        href: https://x.com/j3suslm
    search: true

format:
  html:
    theme: [flatly, custom.scss]
    link-color: #5d6d7e
    css: styles.css
