project:
  type: website
  output-dir: _output

website:
  title: "Jesus LM"
  page-navigation: true
  page-footer:
    background: "#f8f8f8"
    center:
      - text: Tableau
        href: https://tinyurl.com/jesus-tableau
      - text: "License"
        href: license.qmd
      - text: "&emsp; &copy; 2025 &emsp;"
      - icon: medium
        href: https://medium.com/@jesuslm
      - icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lm
      - icon: twitter
        href: https://x.com/j3suslm

  navbar:
    title: Home
    background: primary
    search: true
    right:
      - href: portfolio/index.qmd
        text: Portfolio
      - icon: medium
        href: https://medium.com/@jesuslm
      - icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lm
      - icon: twitter
        href: https://x.com/j3suslm
  
  sidebar:
    foreground: primary
    collapse-level: 1
    style: "docked"
    border: false
    contents:
      - section: Articles
        contents:
        - text: "BI with SQL & Markdown"
          href: evidence.qmd
        - text: BI as Code
          href: bi_as_code.qmd
        - text: Docs as Code
          href: docs_as_code.qmd
        - text: Slides as Code
          href: slides_as_code.qmd
        - text: Duckdb & Evidence
          href: duckdb_bi.qmd
        - text: Duckdb & Google Sheets
          href: duckdb_gsheets.qmd
        - text: Judiciary Elections in Mexico
          href: judiciary_elections.qmd
        - text: Social Security in Mexico
          href: social_security_mexico.qmd
        - text: National Guard in Mexico
          href: national_guard.qmd
        - text: The Economist & Data Scientist Role in Public Security
          href: public_security.qmd
      - section: Reports
        contents:
        - text: Cluster analysis with Python and Polars
          href: clustering.qmd
        - text: Plotting with ggplot2 in Python
          href: plotnine.qmd
        - text: Understanding Spotify User Behavior
          href: spotify.qmd
        - text: Gasoline Prices in Mexico
          href: gasoline_web_nocode.qmd
        - text: Farmacias Similares Locations
          href: farmacias_similares.qmd
      - section: Slideshows
        contents:
        - text: Gasoline Prices in Mexico
          href: gasoline_web_slides.qmd
        - text: Water Collection Systems in Mexico
          href: water_collection_slides.qmd
        - text: RIP Lake Zumpango, Mexico
          href: zumpango_slides.qmd
      - section: Dashboards
        contents:
        - text: Gasoline Prices in Mexico
          href: gasoline_dashboard.qmd
      - section: Other Resources
        contents:
        - text: Farmacias Similares Dashboard
          href: https://j3suslm-fsdashboard.evidence.app
        - text: Mexico City Crime Dashboard
          href: https://j3susl-monroy.evidence.app
        - text: Why BI tools Fall short
          href: https://j3suslm.github.io/Projects/posts/why_bi_tools_fall_short_github.html
        - text: Window Functions in SQL
          href: https://j3suslm.github.io/Projects/posts/sql_wf_github.html
        - text: Dashboards vs Web reports
          href: https://j3suslm.github.io/Projects/posts/reporting_github.html#1  

format:
  html:
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 200px
      gutter-width: 1em
    theme:
      - flatly
    css: styles.css
    toc: true
    toc-title: Table of Contents
    toc-expand: 3
